version: '3.8'
services:
  h2:
    image: oscarfonts/h2:latest
    ports:
      - "1521:1521"
    volumes:
      - h2-data:/opt/h2-data
    environment:
      - H2_OPTIONS=-tcp -tcpAllowOthers -tcpPort 1521 -ifNotExists

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - h2
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:tcp://h2:1521/./test
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=

volumes:
  h2-data:
