INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO) VALUES ('CELULAR', 'GALAXY', 5000);
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO) VALUES ('CADEIRA', 'GAMER', 350);
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO) VALUES ('NOTEBOOK', 'I7 16GBS', 4800);
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO) VALUES ('ALEXA', 'FALA MUITO', 200);
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO) VALUES ('IMPRESSORA', 'JATO DE TINTA', 1500);